# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rules/alert.rules"
  - "rules/recording.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Where to look for exporters
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # PROMETHEUS
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  # KAFKA
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.2.15:7071']

  # ELK
  - job_name: 'elasticsearch'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9200']

  # KUBERNETES
  - job_name: 'kubernetes'
    scrape_interval: 10s
    static_configs:
      - targets: ['10.0.2.15:30000']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  #     static_configs:
  #          - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - 'tasks.node-exporter'
        type: 'A'
        port: 9100

#     static_configs:
#          - targets: ['node-exporter:9100']
